### ISSUE TITLE
CsWinRT Projection Assembly throws Activation error

### ISSUE THREAD

**Issue by KenAdamson** [microsoft/winrtc#144]
When attempting to instantiate a Microsoft.WinRTC.WebRtcWrapper.rtc.Thread, the WinRT.BaseActivationFactory throws an TargetInvocationException - Class not registered.  

1. Create C# projection assembly (in order to get it to compile, you must use  Microsoft.Windows.CsWinRT 1.3.5) - expose the following namespaces:
```
		<CsWinRTIncludes>
			Microsoft.WinRTC.WebRtcWrapper.webrtc;
			Microsoft.WinRTC.WebRtcWrapper.rtc;
			Microsoft.WinRTC.WebRtcWrapper.rtc.factory_implementation;
			Microsoft.WinRTC.WebRtcWrapper.cricket;
			Microsoft.WinRTC.WebRtcWrapper.webrtc.PeerConnection;
			Microsoft.WinRTC.WebRtcWrapper.webrtc.PeerConnectionFactory;
			Microsoft.WinRTC.WebRtcWrapper.webrtc.VideoFrame;
			webrtc
		</CsWinRTIncludes>
```

The nuspec for this project contains the following dependencies:

```
		<dependencies>
			<group targetFramework="net6.0-windows10.0.19041.0" />
			<group targetFramework=".NETCoreApp3.0" />
			<group targetFramework="UAP10.0" />
			<group targetFramework=".NETFramework4.6" />
		</dependencies>
```

2. Create a Console App which references the nuget package via local repository
3. In Program.cs, paste the following (adapted from the XAML component in the samples):

```
using Microsoft.WinRTC.WebRtcWrapper.webrtc;
using Microsoft.WinRTC.WebRtcWrapper.webrtc.PeerConnection;

var networkThread = Microsoft.WinRTC.WebRtcWrapper.rtc.Thread.CreateWithSocketServer();
networkThread.Name = "pc_network_thread";
networkThread.Start();

var workerThread = Microsoft.WinRTC.WebRtcWrapper.rtc.Thread.Create();
workerThread.Name = "pc_worker_thread";
workerThread.Start();

var signalingThread = Microsoft.WinRTC.WebRtcWrapper.rtc.Thread.Create();
signalingThread.Name = "pc_signaling_thread";
signalingThread.Start();

var audioEncoderFactory = WebRTC.CreateBuiltinAudioEncoderFactory();
var audioDecoderFactory = WebRTC.CreateBuiltinAudioDecoderFactory();
var videoDecoderFactory = WebRTC.CreateBuiltinVideoDecoderFactory();
var videoEncoderFactory = WebRTC.CreateBuiltinVideoEncoderFactory();

var peerConnectionFactory = new PeerConnectionFactory(networkThread,
    workerThread,
    signalingThread,
    audioEncoderFactory,
    audioDecoderFactory,
    videoEncoderFactory,
    videoDecoderFactory);

var config = new RTCConfiguration
{
    SdpSemantics = SdpSemantics.UnifiedPlan
};
// populate ice servers via (maybe) a signaling call
var iceServer = new IceServer
{
    Urls = new List<string> { "stun:stun.l.google.com:19302" }
};
config.IceServers.Add(iceServer);

var peerConnectionObserver = new PeerConnectionObserver();
peerConnectionObserver.OnIceCandidate += Console.WriteLine;

var peerConnectionDependencies = new PeerConnectionDependencies(peerConnectionObserver);

var peerConnection = peerConnectionFactory.CreatePeerConnection(config, peerConnectionDependencies);

Console.WriteLine(peerConnection);

```
4. Run, observe error

**Expected behavior**
Thread class is constructed without throwing COM Activation error.

**Screenshots**
<attached>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A

**Smartphone (please complete the following information):**
N/A

![stacktrace](https://user-images.githubusercontent.com/2451298/157503885-72dab5ec-7225-464f-b4a8-e67a4d312ece.png)

**Comment by KenAdamson** [comment]
Actually, I just realized that it looks like accessing any static (factory) method is broken.  I changed the Program.cs to just be:

```
using Microsoft.WinRTC.WebRtcWrapper.webrtc;

var audioEncoderFactory = WebRTC.CreateBuiltinAudioEncoderFactory();
```

- and received the same error, but complaining about a different type:

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Microsoft.WinRTC.WebRtcWrapper.webrtc.WebRTC._IWebRTCStatics..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.WinRTC.WebRtcWrapper.webrtc.WebRTC._IWebRTCStatics.get_Instance()
   at Microsoft.WinRTC.WebRtcWrapper.webrtc.WebRTC.CreateBuiltinAudioEncoderFactory()
   at Program.<Main>$(String[] args) in E:\src\livingExp\winrtc-interop\WinRTCTest\Program.cs:line 16
```

**Comment by KenAdamson** [comment]
And, attempting to instantiate non-static types doesn't work either.  Here, I am attempting to new-up an RTCConfiguration object:

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.WinRTC.WebRtcWrapper.webrtc.PeerConnection.RTCConfiguration..ctor()
   at Program.<Main>$(String[] args) in E:\src\livingExp\winrtc-interop\WinRTCTest\Program.cs:line 29
```

**Comment by KenAdamson** [comment]
I produced a much-simplified solution which mirrors this architecture:  static lib project which exports a trivial "add" function, a UWP C++/WinRT DLL which links to and projects the static lib, and a C#/WinRT assembly which projects that.  Same results:

![image](https://user-images.githubusercontent.com/2451298/157913410-236c4753-5a78-47a0-8e25-89fc4e425316.png)

**Comment by KenAdamson** [comment]
Using dotPeek to inspect the winmd built by the C++/WinRT DLL component, I see the namespace, class and method:

![image](https://user-images.githubusercontent.com/2451298/157940570-cf3cb2c2-9500-416f-b45e-cb4716ac7720.png)

**Comment by KenAdamson** [comment]
Maybe this is the solution?

https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/
